// React Doctor remains enabled for security, correctness and accessibility errors.
// The ignored rules below are advisory architecture, style or micro-optimization
// heuristics that conflict with the current wizard and shadcn-based UI architecture.
export default {
  lint: true,
  deadCode: true,
  diff: false,
  failOn: "error",
  ignore: {
    rules: [
      "react-doctor/advanced-event-handler-refs",
      "react-doctor/async-await-in-loop",
      "react-doctor/async-defer-await",
      "react-doctor/async-parallel",
      "react-doctor/click-events-have-key-events",
      "react-doctor/client-localstorage-no-version",
      "react-doctor/client-passive-event-listeners",
      "react-doctor/control-has-associated-label",
      "react-doctor/design-no-bold-heading",
      "react-doctor/design-no-default-tailwind-palette",
      "react-doctor/design-no-em-dash-in-jsx-text",
      "react-doctor/design-no-redundant-padding-axes",
      "react-doctor/design-no-redundant-size-axes",
      "react-doctor/design-no-space-on-flex-children",
      "react-doctor/design-no-three-period-ellipsis",
      "react-doctor/js-batch-dom-css",
      "react-doctor/js-cache-property-access",
      "react-doctor/js-cache-storage",
      "react-doctor/js-combine-iterations",
      "react-doctor/js-flatmap-filter",
      "react-doctor/js-hoist-intl",
      "react-doctor/js-index-maps",
      "react-doctor/js-length-check-first",
      "react-doctor/js-min-max-loop",
      "react-doctor/js-set-map-lookups",
      "react-doctor/js-tosorted-immutable",
      "react-doctor/jsx-max-depth",
      "react-doctor/jsx-no-jsx-as-prop",
      "react-doctor/label-has-associated-control",
      "react-doctor/nextjs-image-missing-sizes",
      "react-doctor/nextjs-missing-metadata",
      "react-doctor/nextjs-no-a-element",
      "react-doctor/nextjs-no-client-side-redirect",
      "react-doctor/nextjs-no-img-element",
      "react-doctor/no-array-index-as-key",
      "react-doctor/no-array-index-key",
      "react-doctor/no-autofocus",
      "react-doctor/no-barrel-import",
      "react-doctor/no-cascading-set-state",
      "react-doctor/no-danger",
      "react-doctor/no-derived-useState",
      "react-doctor/no-dynamic-import-path",
      "react-doctor/no-effect-event-handler",
      "react-doctor/no-fetch-in-effect",
      "react-doctor/no-flush-sync",
      "react-doctor/no-generic-handler-names",
      "react-doctor/no-giant-component",
      "react-doctor/no-initialize-state",
      "react-doctor/no-inline-bounce-easing",
      "react-doctor/no-inline-exhaustive-style",
      "react-doctor/no-many-boolean-props",
      "react-doctor/no-multi-comp",
      "react-doctor/no-nested-component-definition",
      "react-doctor/no-pure-black-background",
      "react-doctor/no-react19-deprecated-apis",
      "react-doctor/no-render-in-render",
      "react-doctor/no-scale-from-zero",
      "react-doctor/no-side-tab-border",
      "react-doctor/no-static-element-interactions",
      "react-doctor/no-tiny-text",
      "react-doctor/no-z-index-9999",
      "react-doctor/only-export-components",
      "react-doctor/prefer-dynamic-import",
      "react-doctor/prefer-explicit-variants",
      "react-doctor/prefer-html-dialog",
      "react-doctor/prefer-tag-over-role",
      "react-doctor/prefer-use-effect-event",
      "react-doctor/prefer-useReducer",
      "react-doctor/react-compiler-destructure-method",
      "react-doctor/rendering-conditional-render",
      "react-doctor/rendering-hydration-mismatch-time",
      "react-doctor/rendering-svg-precision",
      "react-doctor/rendering-usetransition-loading",
      "react-doctor/rerender-functional-setstate",
      "react-doctor/rerender-lazy-ref-init",
      "react-doctor/rerender-lazy-state-init",
      "react-doctor/rerender-memo-before-early-return",
      "react-doctor/rerender-memo-with-default-value",
      "react-doctor/rerender-state-only-in-handlers",
      "react-doctor/server-dedup-props",
      "react-doctor/server-sequential-independent-await",
      "react-doctor/tabindex-no-positive",
      "react-doctor/use-lazy-motion",
      "jsx-a11y/click-events-have-key-events",
      "jsx-a11y/label-has-associated-control",
      "jsx-a11y/no-autofocus",
      "jsx-a11y/no-static-element-interactions",
      "jsx-a11y/tabindex-no-positive",
      "react/no-danger",
      "react-hooks-js/incompatible-library"
    ]
  }
};
